### ISSUE TITLE
Indexers returning null pointer errors on tag latest/ls60

### ISSUE THREAD

**Issue by Kline-** [linuxserver/docker-nzbhydra2#18]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Indexers shouldn't return null pointer errors.

## Current Behavior

Both manual and automated searches cause a number of indexers such as Drunken Slug to return a null pointer error

## Steps to Reproduce

1. Add Drunken Slug as an indexer in hydra settings and let it check capabilities.
2. Observe log errors that DS returns null on any query.
Example URL that works fine in curl and works fine on tag ls47: https://drunkenslug.com/api?apikey=<apikey>&t=search&extended=1&q=sonic&password=1&limit=1000&offset=0

This same URL returns errors when hydra queries it on ls60 base images.

## Environment
**OS:** Debian/testing
**CPU architecture:** x86_64
**How docker service was installed:** Docker hub image

## Command used to create docker container (run/create/compose/screenshot)
<pre>
  nzbhydra2:
    container_name: "nzbhydra2"
    #image: "linuxserver/nzbhydra2:latest"
    image: "linuxserver/nzbhydra2:v4.3.0-ls47"
    depends_on:
      - "nzbget"
    environment:
      - "PUID=1004"
      - "PGID=1004"
      - "TZ=America/Chicago"
    networks:
      - "bridge"
    ports:
      - "127.0.0.1:9030:5076"
    restart: "unless-stopped"
    volumes:
      - "/config/nzbhydra2:/config"</pre>
## Docker logs
<pre>2022-04-25 04:49:18.251  INFO --- [http-nio-0.0.0.0-5] o.n.indexers.capscheck.IndexerChecker    : [ID: 71355, Host: 172.20.0.1] Will check capabilities of indexer Drunken Slug using 2 concurrent connections and a delay of 1000ms
2022-04-25 04:49:22.851  INFO --- [ pool-501-thread-1] o.n.indexers.capscheck.IndexerChecker    : [ID: 71355, Host: 172.20.0.1] Indexer Drunken Slug probably supports the ID type TVIMDB. 100.0% of results were correct.
2022-04-25 04:49:24.409 ERROR --- [http-nio-0.0.0.0-5] o.n.indexers.capscheck.IndexerChecker    : [ID: 71355, Host: 172.20.0.1] Error while communicating with indexer: org.nzbhydra.indexers.exceptions.IndexerUnreachableException: Error while communicating with indexer Drunken Slug. Server returned: java.lang.NullPointerException
2022-04-25 04:49:24.409 ERROR --- [http-nio-0.0.0.0-5] o.n.indexers.capscheck.IndexerChecker    : [ID: 71355, Host: 172.20.0.1] Error while communicating with indexer: org.nzbhydra.indexers.exceptions.IndexerUnreachableException: Error while communicating with indexer Drunken Slug. Server returned: java.lang.NullPointerException
2022-04-25 04:49:24.411  INFO --- [http-nio-0.0.0.0-5] o.n.indexers.capscheck.IndexerChecker    : [ID: 71355, Host: 172.20.0.1] Determined an api hit limit of 1000 and a download limit of 100
2022-04-25 04:49:24.656  INFO --- [http-nio-0.0.0.0-5] o.n.indexers.capscheck.IndexerChecker    : [ID: 71355, Host: 172.20.0.1] Indexer Drunken Slug supports the following search types: TVSEARCH
2022-04-25 04:52:50.769  INFO --- [http-nio-0.0.0.0-5] o.n.indexers.capscheck.IndexerChecker    : [ID: 71355, Host: 172.20.0.1] Will check capabilities of indexer Drunken Slug using 2 concurrent connections and a delay of 1000ms
2022-04-25 04:52:53.734  INFO --- [ pool-510-thread-2] o.n.indexers.capscheck.IndexerChecker    : [ID: 71355, Host: 172.20.0.1] Indexer Drunken Slug probably supports the ID type TVMAZE. 100.0% of results were correct.
2022-04-25 04:52:55.193  INFO --- [ pool-510-thread-2] o.n.indexers.capscheck.IndexerChecker    : [ID: 71355, Host: 172.20.0.1] Indexer Drunken Slug probably supports the ID type TVIMDB. 100.0% of results were correct.
2022-04-25 04:52:56.710 ERROR --- [http-nio-0.0.0.0-5] o.n.indexers.capscheck.IndexerChecker    : [ID: 71355, Host: 172.20.0.1] Error while communicating with indexer: org.nzbhydra.indexers.exceptions.IndexerUnreachableException: Error while communicating with indexer Drunken Slug. Server returned: java.lang.NullPointerException
2022-04-25 04:52:56.711  INFO --- [http-nio-0.0.0.0-5] o.n.indexers.capscheck.IndexerChecker    : [ID: 71355, Host: 172.20.0.1] Determined an api hit limit of 1000 and a download limit of 100
2022-04-25 04:52:56.931  INFO --- [http-nio-0.0.0.0-5] o.n.indexers.capscheck.IndexerChecker    : [ID: 71355, Host: 172.20.0.1] Indexer Drunken Slug supports the following search types: TVSEARCH
2022-04-25 04:53:17.486  INFO --- [http-nio-0.0.0.0-5] org.nzbhydra.config.ConfigWeb            : [ID: 12195, Host: 172.20.0.1] Received new config
2022-04-25 04:53:17.618  INFO --- [http-nio-0.0.0.0-5] o.n.searching.SearchModuleProvider       : [ID: 12195, Host: 172.20.0.1] Initializing indexer 6box
2022-04-25 04:53:17.622  INFO --- [http-nio-0.0.0.0-5] o.n.searching.SearchModuleProvider       : [ID: 12195, Host: 172.20.0.1] Initializing indexer Binsearch
2022-04-25 04:53:17.624  INFO --- [http-nio-0.0.0.0-5] o.n.searching.SearchModuleProvider       : [ID: 12195, Host: 172.20.0.1] Initializing indexer Drunken Slug
2022-04-25 04:53:17.635  INFO --- [http-nio-0.0.0.0-5] o.n.searching.SearchModuleProvider       : [ID: 12195, Host: 172.20.0.1] Initializing indexer NZB Finder
2022-04-25 04:53:17.637  INFO --- [http-nio-0.0.0.0-5] o.n.searching.SearchModuleProvider       : [ID: 12195, Host: 172.20.0.1] Initializing indexer NzBNooB
2022-04-25 04:53:17.638  INFO --- [http-nio-0.0.0.0-5] o.n.searching.SearchModuleProvider       : [ID: 12195, Host: 172.20.0.1] Initializing indexer anizb
2022-04-25 04:53:17.640  INFO --- [http-nio-0.0.0.0-5] o.n.searching.SearchModuleProvider       : [ID: 12195, Host: 172.20.0.1] Initializing indexer fastNZB
2022-04-25 04:53:17.645  INFO --- [http-nio-0.0.0.0-5] o.n.a.HydraAnonymousAuthenticationFilter : [ID: 12195, Host: 172.20.0.1] Granting basic user rights to anonymous users
2022-04-25 04:53:17.645  INFO --- [http-nio-0.0.0.0-5] o.n.a.HydraAnonymousAuthenticationFilter : [ID: 12195, Host: 172.20.0.1] Granting admin rights to anonymous users
2022-04-25 04:53:17.646  INFO --- [http-nio-0.0.0.0-5] o.n.d.downloaders.DownloaderProvider     : [ID: 12195, Host: 172.20.0.1] Initializing downloader NZBGet
2022-04-25 04:53:18.766 ERROR --- [http-nio-0.0.0.0-5] o.a.c.c.C.[.[.[.[dispatcherServlet]      : [ID: 85076, Host: 172.20.0.1] Servlet.service() for servlet [dispatcherServlet] in context with path [/nzbhydra] threw exception [Request processing failed; nested exception is java.lang.IllegalArgumentException: argument "content" is null] with root cause
java.lang.IllegalArgumentException: argument "content" is null
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3612)
        at org.nzbhydra.update.UpdateManager.getReleases(UpdateManager.java:389)
        at com.google.common.base.Suppliers$ExpiringMemoizingSupplier.get(Suppliers.java:187)
        at org.nzbhydra.update.UpdateManager.getUpdateInfo(UpdateManager.java:141)
        at com.google.common.base.Suppliers$ExpiringMemoizingSupplier.get(Suppliers.java:187)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
</pre>

**Comment by djsly** [comment]
Same here.  Drunken slug isn't working. I though it was them but it does look like something specific to this docket image.

**Comment by memmnon** [comment]
I had the same issue with DS. Reverting to the previous release fixes.

**Comment by tofuSCHNITZEL** [comment]
> I had the same issue with DS. Reverting to the previous release fixes.

have the same issue,. Lots of different indexers are producing a nullpointer exception. which tag did you revert to?

**Comment by Kline-** [comment]
@tofuSCHNITZEL From my docker-compose snippet above, `linuxserver/nzbhydra2:v4.3.0-ls47` seems to be working 100% ok still.

**Comment by thespad** [comment]
Can you please try with `v4.3.1-ls52` (or just re-pull `latest`). There were some DNS related issues with the Alpine baseimage that were affecting some people so we've switched back to Ubuntu on the stable branch for now.

**Comment by Kline-** [comment]
Seems to be resolved with `v4.3.1-ls52`. Everything looks to be working ok after a few test searches that previously produced the errors. Not seeing anything wrong in the logs either.
