### ISSUE TITLE
[BUG] Version 5.0 docker image fails to start on ARM v7 - "[Errno 8] Exec format error: './core'"

### ISSUE THREAD

**Issue by sunrisepi** [linuxserver/docker-nzbhydra2#38]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi.  Version 5.0 of the docker image breaks (will not successfully start) on ARM v7, beginning with **linuxserver/nzbhydra2:arm32v7-dev-v5.0.4-ls96**.  I also tried the most recent/latest version (**linuxserver/nzbhydra2:latest**) as of about 2 hours ago and it also fails.

The last working version (docker image starts and runs OK) is **linuxserver/nzbhydra2:arm32v7-4.7.6-dev**.  I retrieved the image versions from https://hub.docker.com/r/linuxserver/nzbhydra2/tags.

When starting any v5.0 build via docker, core fails to execute.  Here is the log.  The error at the end loops, can't start core.  I will use version 4.7.6-dev until version 5.0 is fixed.  Thanks for looking into this!

```
Container started
01/22/2023 10:27:26 AM
[migrations] started
01/22/2023 10:27:26 AM
[migrations] no migrations found
01/22/2023 10:27:26 AM
01/22/2023 10:27:26 AM
-------------------------------------
01/22/2023 10:27:26 AM
          _         ()
01/22/2023 10:27:26 AM
         | |  ___   _    __
01/22/2023 10:27:26 AM
         | | / __| | |  /  \
01/22/2023 10:27:26 AM
         | | \__ \ | | | () |
01/22/2023 10:27:26 AM
         |_| |___/ |_|  \__/
01/22/2023 10:27:26 AM
01/22/2023 10:27:26 AM
01/22/2023 10:27:26 AM
Brought to you by linuxserver.io
01/22/2023 10:27:26 AM
-------------------------------------
01/22/2023 10:27:26 AM
01/22/2023 10:27:26 AM
To support the app dev(s) visit:
01/22/2023 10:27:26 AM
NZBHydra 2: https://github.com/theotherp/nzbhydra2#donate
01/22/2023 10:27:26 AM
01/22/2023 10:27:26 AM
To support LSIO projects visit:
01/22/2023 10:27:26 AM
https://www.linuxserver.io/donate/
01/22/2023 10:27:26 AM
-------------------------------------
01/22/2023 10:27:26 AM
GID/UID
01/22/2023 10:27:26 AM
-------------------------------------
01/22/2023 10:27:26 AM
01/22/2023 10:27:26 AM
User uid:    1000
01/22/2023 10:27:26 AM
User gid:    1000
01/22/2023 10:27:26 AM
-------------------------------------
01/22/2023 10:27:26 AM
01/22/2023 10:27:26 AM
Logging wrapper output to /config/logs/wrapper.log
01/22/2023 10:27:26 AM
Traceback (most recent call last):
01/22/2023 10:27:26 AM
  File "/app/nzbhydra2/nzbhydra2wrapperPy3.py", line 714, in <module>
01/22/2023 10:27:26 AM
    main(sys.argv[1:])
01/22/2023 10:27:26 AM
  File "/app/nzbhydra2/nzbhydra2wrapperPy3.py", line 623, in main
01/22/2023 10:27:26 AM
    setupLogger()
01/22/2023 10:27:26 AM
  File "/app/nzbhydra2/nzbhydra2wrapperPy3.py", line 162, in setupLogger
01/22/2023 10:27:26 AM
    file_logger = RotatingFileHandler(filename=logfilename, maxBytes=100000, backupCount=1)
01/22/2023 10:27:26 AM
  File "/usr/lib/python3.10/logging/handlers.py", line 155, in __init__
01/22/2023 10:27:26 AM
    BaseRotatingHandler.__init__(self, filename, mode, encoding=encoding,
01/22/2023 10:27:26 AM
  File "/usr/lib/python3.10/logging/handlers.py", line 58, in __init__
01/22/2023 10:27:26 AM
    logging.FileHandler.__init__(self, filename, mode=mode,
01/22/2023 10:27:26 AM
  File "/usr/lib/python3.10/logging/__init__.py", line 1169, in __init__
01/22/2023 10:27:26 AM
    StreamHandler.__init__(self, self._open())
01/22/2023 10:27:26 AM
  File "/usr/lib/python3.10/logging/__init__.py", line 1201, in _open
01/22/2023 10:27:26 AM
    return open_func(self.baseFilename, self.mode,
01/22/2023 10:27:26 AM
PermissionError: [Errno 13] Permission denied: '/config/logs/wrapper.log'
01/22/2023 10:27:27 AM
[custom-init] No custom files found, skipping...
01/22/2023 10:27:27 AM
Logging wrapper output to /config/logs/wrapper.log
01/22/2023 10:27:27 AM
2023-01-22 10:27:27,920  INFO - Determined release type: native
01/22/2023 10:27:27 AM
2023-01-22 10:27:27,924  INFO - Starting NZBHydra main process with command line: ./core -Xmx256M -DfromWrapper=true -DinternalApiKey=wibusnqxjvbocizrbjon -Dspring.output.ansi.enabled=ALWAYS --nobrowser --datafolder /config in folder /app/nzbhydra2
01/22/2023 10:27:27 AM
2023-01-22 10:27:27,936  ERROR - Unable to start process; make sure "core" exists and is executable. Error message: [Errno 8] Exec format error: './core'
01/22/2023 10:27:28 AM
Logging wrapper output to /config/logs/wrapper.log
01/22/2023 10:27:28 AM
2023-01-22 10:27:28,983  INFO - Determined release type: native
01/22/2023 10:27:28 AM
2023-01-22 10:27:28,987  INFO - Starting NZBHydra main process with command line: ./core -Xmx256M -DfromWrapper=true -DinternalApiKey=pbudesjktuqjgubhgegu -Dspring.output.ansi.enabled=ALWAYS --nobrowser --datafolder /config in folder /app/nzbhydra2
01/22/2023 10:27:28 AM
2023-01-22 10:27:28,994  ERROR - Unable to start process; make sure "core" exists and is executable. Error message: [Errno 8] Exec format error: './core'
01/22/2023 10:27:30 AM
Logging wrapper output to /config/logs/wrapper.log

```

### Expected Behavior

Below is the startup log from a working version (4.7.6-dev) and the broken version (v5.0).  I noticed the execution line is different.  This is likely the cause of the failure.

**v4.7.6-dev:**

> INFO - Starting NZBHydra main process with command line: java -Xmx256M -DfromWrapper -XX:TieredStopAtLevel=1 -noverify -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/config/logs -Dspring.output.ansi.enabled=ALWAYS -jar /app/nzbhydra2/bin/lib/core-4.7.6-exec.jar --nobrowser --datafolder /config in folder /app/nzbhydra2/bin

**v5.0:**
> INFO - Starting NZBHydra main process with command line: ./core -Xmx256M -DfromWrapper=true -DinternalApiKey=wibusnqxjvbocizrbjon -Dspring.output.ansi.enabled=ALWAYS --nobrowser --datafolder /config in folder /app/nzbhydra2

**And now the startup log from a working version (4.7.6-dev):**
```
01/22/2023 10:36:12 AM
[custom-init] No custom files found, skipping...
01/22/2023 10:36:13 AM
Logging wrapper output to /config/logs/wrapper.log
01/22/2023 10:36:13 AM
2023-01-22 10:36:13,589  INFO - Determined java version as '17' from version string 'openjdk version "17.0.5" 2022-10-18'
01/22/2023 10:36:13 AM
2023-01-22 10:36:13,590  INFO - Starting NZBHydra main process with command line: java -Xmx256M -DfromWrapper -XX:TieredStopAtLevel=1 -noverify -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/config/logs -Dspring.output.ansi.enabled=ALWAYS -jar /app/nzbhydra2/bin/lib/core-4.7.6-exec.jar --nobrowser --datafolder /config in folder /app/nzbhydra2/bin
01/22/2023 10:36:13 AM
OpenJDK Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
```

### Steps To Reproduce

Pull any v5.0 version of the docker image for ARM 32-bit (v7) and it will fail as noted above.

### Environment

```markdown
- OS:Raspbian GNU/Linux 10 (buster)
- How docker service was installed: Via command line
```

### CPU architecture

armhf

### Docker creation

```bash
nzbhydra2:
    image: lscr.io/linuxserver/nzbhydra2:arm32v7-dev-v5.0.4-ls96
    container_name: nzbhydra
    network_mode: "host"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /home/pi/dockerapps/linuxserver-nzbhydra2/blackhole:/blackhole
      - /home/pi/dockerapps/linuxserver-nzbhydra2/config:/config
      - /home/pi/dockerapps/linuxserver-nzbhydra2/downloads:/downloads
    restart: unless-stopped
```

### Container logs

```bash
See above
```

**Comment by thespad** [comment]
We are aware. We're evaluating options for continued support of armhf but in the meantime please roll back to the last 4.x release.

**Comment by thespad** [comment]
Can you please try with (and I cannot stress this enough) a **copy** of your data and this image `lspipepr/nzbhydra2:dev-v5.1.0-pkg-948d5790-pr-39`.

**Comment by sunrisepi** [comment]
Thanks, @thespad.  That works.  It now starts OK!  I used **image: lspipepr/nzbhydra2:dev-v5.1.0-pkg-948d5790-pr-39** as you directed.  

I used this on a backup of my data and the docker container executes fine.  I noticed the first time I ran this it had to upgrade/migrate the nzb database version (I think from 1.4 to 2.0).  That migrated OK.

Also navigated UI, noticed everything is OK.  Able to search for stuff, add it for download and have that successfully done as well.  The image looks good from what I can see.  Looking forward to seeing this added to the main docker repo.

I noticed the command line is now:

> 2023-01-22 12:46:03,921  INFO - Starting NZBHydra main process with command line: java -Xmx256M -DfromWrapper=true -DinternalApiKey=ggqjpmylbqkbqlvwcsdj -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/config/logs -Dspring.output.ansi.enabled=ALWAYS -jar /app/nzbhydra2/lib/core-5.1.0-exec.jar --nobrowser --datafolder /config in folder /app/nzbhydra2

Here's some output showing it started successfully.  Not including everything as this would be a very long post with that.
```
01/22/2023 12:46:02 PM
Logging wrapper output to /config/logs/wrapper.log
01/22/2023 12:46:02 PM
Traceback (most recent call last):
01/22/2023 12:46:02 PM
  File "/app/nzbhydra2/nzbhydra2wrapperPy3.py", line 714, in <module>
01/22/2023 12:46:02 PM
    main(sys.argv[1:])
01/22/2023 12:46:02 PM
  File "/app/nzbhydra2/nzbhydra2wrapperPy3.py", line 623, in main
01/22/2023 12:46:02 PM
    setupLogger()
01/22/2023 12:46:02 PM
  File "/app/nzbhydra2/nzbhydra2wrapperPy3.py", line 162, in setupLogger
01/22/2023 12:46:02 PM
    file_logger = RotatingFileHandler(filename=logfilename, maxBytes=100000, backupCount=1)
01/22/2023 12:46:02 PM
  File "/usr/lib/python3.10/logging/handlers.py", line 155, in __init__
01/22/2023 12:46:02 PM
    BaseRotatingHandler.__init__(self, filename, mode, encoding=encoding,
01/22/2023 12:46:02 PM
  File "/usr/lib/python3.10/logging/handlers.py", line 58, in __init__
01/22/2023 12:46:02 PM
    logging.FileHandler.__init__(self, filename, mode=mode,
01/22/2023 12:46:02 PM
  File "/usr/lib/python3.10/logging/__init__.py", line 1169, in __init__
01/22/2023 12:46:02 PM
    StreamHandler.__init__(self, self._open())
01/22/2023 12:46:02 PM
  File "/usr/lib/python3.10/logging/__init__.py", line 1201, in _open
01/22/2023 12:46:02 PM
    return open_func(self.baseFilename, self.mode,
01/22/2023 12:46:02 PM
PermissionError: [Errno 13] Permission denied: '/config/logs/wrapper.log'
01/22/2023 12:46:02 PM
[custom-init] No custom files found, skipping...
01/22/2023 12:46:03 PM
Logging wrapper output to /config/logs/wrapper.log
01/22/2023 12:46:03 PM
2023-01-22 12:46:03,728  INFO - Determined release type: generic
01/22/2023 12:46:03 PM
2023-01-22 12:46:03,920  INFO - Determined java version as '17' from version string 'openjdk version "17.0.5" 2022-10-18'
01/22/2023 12:46:03 PM
2023-01-22 12:46:03,921  INFO - Starting NZBHydra main process with command line: java -Xmx256M -DfromWrapper=true -DinternalApiKey=ggqjpmylbqkbqlvwcsdj -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/config/logs -Dspring.output.ansi.enabled=ALWAYS -jar /app/nzbhydra2/lib/core-5.1.0-exec.jar --nobrowser --datafolder /config in folder /app/nzbhydra2
01/22/2023 12:46:06 PM
12:46:06.711 [main] INFO org.nzbhydra.NzbHydra - Version: 5.1.0
01/22/2023 12:46:06 PM
12:46:06.731 [main] INFO org.nzbhydra.NzbHydra - Build timestamp: 2023-01-22 19:26
[... lots of lines ommitted ...]
01/22/2023 1:01:19 PM
2023-01-22 13:01:19.714  INFO --- [              main] o.s.m.s.b.SimpleBrokerMessageHandler     : Started.
01/22/2023 1:01:19 PM
[ls.io-init] done.
01/22/2023 1:01:19 PM
2023-01-22 13:01:19.896  INFO --- [              main] org.nzbhydra.NzbHydra                    : Started NzbHydra in 50.247 seconds (process running for 57.922)
01/22/2023 1:01:20 PM
2023-01-22 13:01:20.400  INFO --- [              main] org.nzbhydra.NzbHydra                    : You seem to be running NZBHydra 2 in docker. You can access Hydra using your local address and the IP you provided
01/22/2023 1:01:27 PM
2023-01-22 13:01:27.641  INFO --- [http-nio-0.0.0.0-5] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
01/22/2023 1:01:27 PM
2023-01-22 13:01:27.644  INFO --- [http-nio-0.0.0.0-5] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
01/22/2023 1:01:27 PM
2023-01-22 13:01:27.651  INFO --- [http-nio-0.0.0.0-5] o.s.web.servlet.DispatcherServlet        : Completed initialization in 4 ms

```

**Comment by thespad** [comment]
PR for dev has been merged, so once that finishes building in ~30 minutes you should be able to update your live instance to the latest version.

**Comment by sunrisepi** [comment]
Thanks, pulled new version (now it's up to 5.1.1) and it works great.  👍
