### ISSUE TITLE
Upgrade to version 5.1.5 java failed?

### ISSUE THREAD

**Issue by BramFr** [linuxserver/docker-nzbhydra2#42]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The website crashed with a java runtime error

### Expected Behavior

New interface with upgrade db to v5

### Steps To Reproduce

kubectl rollout restart deployment hydra

using the latest version.

### Environment

```markdown
- OS: Debian GNU/Linux 11 (bullseye)
- usning kubernetes
```

### CPU architecture

x86-64

### Docker creation

```bash
Dont have one.
```

### Container logs

```bash
2023-02-23 07:38:50,582  INFO - Determined release type: native
2023-02-23 07:38:50,584  INFO - Starting NZBHydra main process with command line: ./core -Xmx256M -DfromWrapper=true -DinternalApiKey=qetrkrvnejshjlzokyhl -Dspring.output.ansi.enabled=ALWAYS --nobrowser --datafolder /config in folder /app/nzbhydra2
07:38:51.881 [main] INFO org.nzbhydra.NzbHydra - Version: 5.1.5
07:38:51.881 [main] INFO org.nzbhydra.NzbHydra - Build timestamp: 2023-02-09 18:37
Exception in thread "main" java.lang.InternalError: java.lang.reflect.InvocationTargetException
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.Metrics.systemMetrics(Metrics.java:67)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.Container.metrics(Container.java:44)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.ContainerInfo.<init>(ContainerInfo.java:34)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.Containers.activeProcessorCount(Containers.java:125)
        at java.base@17.0.5/java.lang.Runtime.availableProcessors(Runtime.java:247)
        at com.fasterxml.jackson.databind.util.internal.PrivateMaxEntriesMap.<clinit>(PrivateMaxEntriesMap.java:136)
        at com.fasterxml.jackson.databind.util.internal.PrivateMaxEntriesMap$Builder.initialCapacity(PrivateMaxEntriesMap.java:1465)
        at com.fasterxml.jackson.databind.util.LRUMap.<init>(LRUMap.java:37)
        at com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector.<init>(JacksonAnnotationIntrospector.java:82)
        at com.fasterxml.jackson.databind.ObjectMapper.<clinit>(ObjectMapper.java:375)
        at org.nzbhydra.Jackson.<clinit>(Jackson.java:35)
        at org.nzbhydra.config.ConfigReaderWriter.validateExistingConfig(ConfigReaderWriter.java:166)
        at org.nzbhydra.NzbHydra.initializeAndValidateAndMigrateYamlFile(NzbHydra.java:245)
        at org.nzbhydra.NzbHydra.startup(NzbHydra.java:173)
        at org.nzbhydra.NzbHydra.main(NzbHydra.java:135)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base@17.0.5/java.lang.reflect.Method.invoke(Method.java:568)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.Metrics.systemMetrics(Metrics.java:63)
        ... 14 more
Caused by: java.lang.ExceptionInInitializerError
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.CgroupSubsystemFactory.create(CgroupSubsystemFactory.java:78)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.CgroupMetrics.getInstance(CgroupMetrics.java:164)
        ... 16 more
Caused by: java.lang.NullPointerException
        at java.base@17.0.5/java.util.Objects.requireNonNull(Objects.java:208)
        at java.base@17.0.5/sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:263)
        at java.base@17.0.5/java.nio.file.Path.of(Path.java:147)
        at java.base@17.0.5/java.nio.file.Paths.get(Paths.java:69)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.CgroupUtil.lambda$readStringValue$0(CgroupUtil.java:57)
        at java.base@17.0.5/java.security.AccessController.executePrivileged(AccessController.java:144)
        at java.base@17.0.5/java.security.AccessController.doPrivileged(AccessController.java:569)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.CgroupUtil.readStringValue(CgroupUtil.java:59)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.CgroupSubsystemController.getStringValue(CgroupSubsystemController.java:66)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.CgroupSubsystemController.getLongValue(CgroupSubsystemController.java:125)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.cgroupv1.CgroupV1Subsystem.getLongValue(CgroupV1Subsystem.java:269)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.cgroupv1.CgroupV1Subsystem.getHierarchical(CgroupV1Subsystem.java:215)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.cgroupv1.CgroupV1Subsystem.setSubSystemControllerPath(CgroupV1Subsystem.java:203)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.cgroupv1.CgroupV1Subsystem.initSubSystem(CgroupV1Subsystem.java:111)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.cgroupv1.CgroupV1Subsystem.<clinit>(CgroupV1Subsystem.java:47)
        ... 18 more
2023-02-23 07:38:51,909  ERROR - Main process shut down unexpectedly. If the wrapper was started in daemon mode you might not see the error output. Start Hydra manually with the same parameters in the same environment to see it
Logging wrapper output to /config/logs/wrapper.log
2023-02-23 07:38:51,993  INFO - Determined release type: native
2023-02-23 07:38:51,994  INFO - Starting NZBHydra main process with command line: ./core -Xmx256M -DfromWrapper=true -DinternalApiKey=mwcyutxtvgvlqlofvmsu -Dspring.output.ansi.enabled=ALWAYS --nobrowser --datafolder /config in folder /app/nzbhydra2
```

**Comment by BramFr** [comment]
After reverting back to image version: 4.7.6 everythings works fine. 
Every v5 version i have this issue.

**Comment by roopesh** [comment]
I'm having the same problem.  But loading 4.7.6 hasn't resolved it for me.

**Comment by BramFr** [comment]
The same issue with 5.1.8

```2023-05-22 10:36:59,531  INFO - Starting NZBHydra main process with command line: ./core -Xmx256M -DfromWrapper=true -DinternalApiKey=bbknoxgoprnmcstdcczc -Dsun.security.pkcs11.enable-solaris=false -Dspring.output.ansi.enabled=ALWAYS --nobrowser --datafolder /config in folder /app/nzbhydra2
10:37:01.207 [main] INFO org.nzbhydra.NzbHydra - Version: 5.1.8
10:37:01.207 [main] INFO org.nzbhydra.NzbHydra - Build timestamp: 2023-03-18 09:59
Exception in thread "main" java.lang.InternalError: java.lang.reflect.InvocationTargetException
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.Metrics.systemMetrics(Metrics.java:67)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.Container.metrics(Container.java:44)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.ContainerInfo.<init>(ContainerInfo.java:34)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.Containers.activeProcessorCount(Containers.java:125)
        at java.base@17.0.5/java.lang.Runtime.availableProcessors(Runtime.java:247)
        at com.fasterxml.jackson.databind.util.internal.PrivateMaxEntriesMap.<clinit>(PrivateMaxEntriesMap.java:136)
        at com.fasterxml.jackson.databind.util.internal.PrivateMaxEntriesMap$Builder.initialCapacity(PrivateMaxEntriesMap.java:1465)
        at com.fasterxml.jackson.databind.util.LRUMap.<init>(LRUMap.java:37)
        at com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector.<init>(JacksonAnnotationIntrospector.java:82)
        at com.fasterxml.jackson.databind.ObjectMapper.<clinit>(ObjectMapper.java:375)
        at org.nzbhydra.Jackson.<clinit>(Jackson.java:35)
        at org.nzbhydra.config.ConfigReaderWriter.validateExistingConfig(ConfigReaderWriter.java:166)
        at org.nzbhydra.NzbHydra.initializeAndValidateAndMigrateYamlFile(NzbHydra.java:245)
        at org.nzbhydra.NzbHydra.startup(NzbHydra.java:173)
        at org.nzbhydra.NzbHydra.main(NzbHydra.java:135)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base@17.0.5/java.lang.reflect.Method.invoke(Method.java:568)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.Metrics.systemMetrics(Metrics.java:63)
        ... 14 more
Caused by: java.lang.ExceptionInInitializerError
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.CgroupSubsystemFactory.create(CgroupSubsystemFactory.java:78)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.CgroupMetrics.getInstance(CgroupMetrics.java:164)
        ... 16 more
Caused by: java.lang.NullPointerException
        at java.base@17.0.5/java.util.Objects.requireNonNull(Objects.java:208)
        at java.base@17.0.5/sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:263)
        at java.base@17.0.5/java.nio.file.Path.of(Path.java:147)
        at java.base@17.0.5/java.nio.file.Paths.get(Paths.java:69)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.CgroupUtil.lambda$readStringValue$0(CgroupUtil.java:57)
        at java.base@17.0.5/java.security.AccessController.executePrivileged(AccessController.java:144)
        at java.base@17.0.5/java.security.AccessController.doPrivileged(AccessController.java:569)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.CgroupUtil.readStringValue(CgroupUtil.java:59)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.CgroupSubsystemController.getStringValue(CgroupSubsystemController.java:66)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.CgroupSubsystemController.getLongValue(CgroupSubsystemController.java:125)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.cgroupv1.CgroupV1Subsystem.getLongValue(CgroupV1Subsystem.java:269)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.cgroupv1.CgroupV1Subsystem.getHierarchical(CgroupV1Subsystem.java:215)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.cgroupv1.CgroupV1Subsystem.setSubSystemControllerPath(CgroupV1Subsystem.java:203)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.cgroupv1.CgroupV1Subsystem.initSubSystem(CgroupV1Subsystem.java:111)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.cgroupv1.CgroupV1Subsystem.<clinit>(CgroupV1Subsystem.java:47)
        ... 18 more
2023-05-22 10:37:01,230  ERROR - Main process shut down unexpectedly. If the wrapper was started in daemon mode you might not see the error output. Start Hydra manually with the same parameters in the same environment to see it
Logging wrapper output to /config/logs/wrapper.log
2023-05-22 10:37:01,311  INFO - Determined release type: native
2023-05-22 10:37:01,320  INFO - Starting NZBHydra main process with command line: ./core -Xmx256M -DfromWrapper=true -DinternalApiKey=svcprwrpkewcausdwjuv -Dsun.security.pkcs11.enable-solaris=false -Dspring.output.ansi.enabled=ALWAYS --nobrowser --datafolder /config in folder /app/nzbhydra2
```

**Comment by j0nnymoe** [comment]
Our tests come back that it works fine: https://ci-tests.linuxserver.io/linuxserver/nzbhydra2/latest/index.html

If you can replicate this when using docker, we'll be able to investigate it but kubernetes (while our containers should work on it) isn't something we provide support for.

**Comment by BramFr** [comment]
Is there anything that i can run with debug mode/logging ?

This is what i used for kubernetes
I have just for a test removed every volume but this get me the same issue/bug.
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hydra
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hydra
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hydra
    spec:
      containers:
        - name: hydra-container
          #image: linuxserver/nzbhydra2:4.7.6
          image: lscr.io/linuxserver/nzbhydra2:latest
          imagePullPolicy: Always
          env:
           - name: PUID
             value: "1000"
           - name: PGID
             value: "1000"
           - name: TZ
             value: "Etc/Amsterdam"
```

Log:
```
[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support the app dev(s) visit:
NZBHydra 2: https://github.com/theotherp/nzbhydra2#donate

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────

Logging wrapper output to /config/logs/wrapper.log
Traceback (most recent call last):
  File "/app/nzbhydra2/nzbhydra2wrapperPy3.py", line 729, in <module>
    main(sys.argv[1:])
  File "/app/nzbhydra2/nzbhydra2wrapperPy3.py", line 635, in main
    setupLogger()
  File "/app/nzbhydra2/nzbhydra2wrapperPy3.py", line 165, in setupLogger
    file_logger = RotatingFileHandler(filename=logfilename, maxBytes=100000, backupCount=1)
  File "/usr/lib/python3.10/logging/handlers.py", line 155, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding=encoding,
  File "/usr/lib/python3.10/logging/handlers.py", line 58, in __init__
    logging.FileHandler.__init__(self, filename, mode=mode,
  File "/usr/lib/python3.10/logging/__init__.py", line 1169, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.10/logging/__init__.py", line 1201, in _open
    return open_func(self.baseFilename, self.mode,
PermissionError: [Errno 13] Permission denied: '/config/logs/wrapper.log'
[custom-init] No custom files found, skipping...
Logging wrapper output to /config/logs/wrapper.log
2023-05-22 11:06:19,241  INFO - Determined release type: native
2023-05-22 11:06:19,244  INFO - Starting NZBHydra main process with command line: ./core -Xmx256M -DfromWrapper=true -DinternalApiKey=ophobkiwhnrtxzyxjduz -Dsun.security.pkcs11.enable-solaris=false -Dspring.output.ansi.enabled=ALWAYS --nobrowser --datafolder /config in folder /app/nzbhydra2
11:06:21.050 [main] INFO org.nzbhydra.NzbHydra - Version: 5.1.8
11:06:21.050 [main] INFO org.nzbhydra.NzbHydra - Build timestamp: 2023-03-18 09:59
Exception in thread "main" java.lang.InternalError: java.lang.reflect.InvocationTargetException
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.Metrics.systemMetrics(Metrics.java:67)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.Container.metrics(Container.java:44)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.ContainerInfo.<init>(ContainerInfo.java:34)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.Containers.activeProcessorCount(Containers.java:125)
        at java.base@17.0.5/java.lang.Runtime.availableProcessors(Runtime.java:247)
        at com.fasterxml.jackson.databind.util.internal.PrivateMaxEntriesMap.<clinit>(PrivateMaxEntriesMap.java:136)
        at com.fasterxml.jackson.databind.util.internal.PrivateMaxEntriesMap$Builder.initialCapacity(PrivateMaxEntriesMap.java:1465)
        at com.fasterxml.jackson.databind.util.LRUMap.<init>(LRUMap.java:37)
        at com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector.<init>(JacksonAnnotationIntrospector.java:82)
        at com.fasterxml.jackson.databind.ObjectMapper.<clinit>(ObjectMapper.java:375)
        at org.nzbhydra.Jackson.<clinit>(Jackson.java:35)
        at org.nzbhydra.config.ConfigReaderWriter.validateExistingConfig(ConfigReaderWriter.java:166)
        at org.nzbhydra.NzbHydra.initializeAndValidateAndMigrateYamlFile(NzbHydra.java:245)
        at org.nzbhydra.NzbHydra.startup(NzbHydra.java:173)
        at org.nzbhydra.NzbHydra.main(NzbHydra.java:135)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base@17.0.5/java.lang.reflect.Method.invoke(Method.java:568)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.Metrics.systemMetrics(Metrics.java:63)
        ... 14 more
Caused by: java.lang.ExceptionInInitializerError
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.CgroupSubsystemFactory.create(CgroupSubsystemFactory.java:78)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.CgroupMetrics.getInstance(CgroupMetrics.java:164)
        ... 16 more
Caused by: java.lang.NullPointerException
        at java.base@17.0.5/java.util.Objects.requireNonNull(Objects.java:208)
        at java.base@17.0.5/sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:263)
        at java.base@17.0.5/java.nio.file.Path.of(Path.java:147)
        at java.base@17.0.5/java.nio.file.Paths.get(Paths.java:69)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.CgroupUtil.lambda$readStringValue$0(CgroupUtil.java:57)
        at java.base@17.0.5/java.security.AccessController.executePrivileged(AccessController.java:144)
        at java.base@17.0.5/java.security.AccessController.doPrivileged(AccessController.java:569)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.CgroupUtil.readStringValue(CgroupUtil.java:59)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.CgroupSubsystemController.getStringValue(CgroupSubsystemController.java:66)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.CgroupSubsystemController.getLongValue(CgroupSubsystemController.java:125)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.cgroupv1.CgroupV1Subsystem.getLongValue(CgroupV1Subsystem.java:269)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.cgroupv1.CgroupV1Subsystem.getHierarchical(CgroupV1Subsystem.java:215)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.cgroupv1.CgroupV1Subsystem.setSubSystemControllerPath(CgroupV1Subsystem.java:203)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.cgroupv1.CgroupV1Subsystem.initSubSystem(CgroupV1Subsystem.java:111)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.containers.cgroupv1.CgroupV1Subsystem.<clinit>(CgroupV1Subsystem.java:47)
        ... 18 more
2023-05-22 11:06:21,067  ERROR - Main process shut down unexpectedly. If the wrapper was started in daemon mode you might not see the error output. Start Hydra manually with the same parameters in the same environment to see it
Logging wrapper output to /config/logs/wrapper.log
2023-05-22 11:06:21,151  INFO - Determined release type: native
```
